### ISSUE TITLE
Week 5 assignment

### ISSUE THREAD

**Issue by AAMerritt109J** [UD-PCS-Foundations-of-R-Fall-2021/week_05#1]
114a442 @rharrington31

**Comment by rharrington31** [comment]
Responding in order:

1. This line of code technically works, but it's not the best way to do this. Once the `url` object has been provided to you, all that you need to do is insert it into `read_csv`: `read_csv(url)`.
2. Good.
3. No need to set up libraries again, it was already done at the top of the script. Also, I highly recommend not putting your API key onto GitHub! Your first attempt here would work, but You never assigned it to an object called `food_stamps`. Instead, you assigned all of the variables via `load_variables` to `food_stamps`.
4. You're using the `pivot_wider` syntax for `pivot_longer` here. Always remember to check the vignette!
5. Correct - why does this matter, though?
6. Your syntax is just about correct. However, you never identify what to join on. You should include something like `by = c("FIPS" = "GEOID")`
7. Just use a `select` statement to order your columns!
8. This would work, though you should still be working with the original column names: `date`, `deaths`, and `County`.
9. This also works, though I'm unsure of where your column names came from.
10. I'd recommend a scatterplot here, though it could work to tell the story you're looking to tell.
